/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Category = IDL.Variant({
  'tee' : IDL.Null,
  'accessory' : IDL.Null,
  'jogger' : IDL.Null,
  'hoodie' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'isNew' : IDL.Bool,
  'priceCents' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addItemToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'removeItemFromCart' : IDL.Func([ProductId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Category = IDL.Variant({
    'tee' : IDL.Null,
    'accessory' : IDL.Null,
    'jogger' : IDL.Null,
    'hoodie' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'isNew' : IDL.Bool,
    'priceCents' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addItemToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeItemFromCart' : IDL.Func([ProductId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };